//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClient.AuctionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auction", Namespace="http://schemas.datacontract.org/2004/07/WcfPr%C3%B8veEksamen")]
    [System.SerializableAttribute()]
    public partial class Auction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BudKundeNavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BudKundeTelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BudPrisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BudTidspunktField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VarebetegnelseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VarenummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VurderingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BudKundeNavn {
            get {
                return this.BudKundeNavnField;
            }
            set {
                if ((object.ReferenceEquals(this.BudKundeNavnField, value) != true)) {
                    this.BudKundeNavnField = value;
                    this.RaisePropertyChanged("BudKundeNavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BudKundeTelefon {
            get {
                return this.BudKundeTelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.BudKundeTelefonField, value) != true)) {
                    this.BudKundeTelefonField = value;
                    this.RaisePropertyChanged("BudKundeTelefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BudPris {
            get {
                return this.BudPrisField;
            }
            set {
                if ((this.BudPrisField.Equals(value) != true)) {
                    this.BudPrisField = value;
                    this.RaisePropertyChanged("BudPris");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BudTidspunkt {
            get {
                return this.BudTidspunktField;
            }
            set {
                if ((this.BudTidspunktField.Equals(value) != true)) {
                    this.BudTidspunktField = value;
                    this.RaisePropertyChanged("BudTidspunkt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Varebetegnelse {
            get {
                return this.VarebetegnelseField;
            }
            set {
                if ((object.ReferenceEquals(this.VarebetegnelseField, value) != true)) {
                    this.VarebetegnelseField = value;
                    this.RaisePropertyChanged("Varebetegnelse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Varenummer {
            get {
                return this.VarenummerField;
            }
            set {
                if ((object.ReferenceEquals(this.VarenummerField, value) != true)) {
                    this.VarenummerField = value;
                    this.RaisePropertyChanged("Varenummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vurdering {
            get {
                return this.VurderingField;
            }
            set {
                if ((this.VurderingField.Equals(value) != true)) {
                    this.VurderingField = value;
                    this.RaisePropertyChanged("Vurdering");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuctionService.IAuctionService")]
    public interface IAuctionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionService/GetAuctions", ReplyAction="http://tempuri.org/IAuctionService/GetAuctionsResponse")]
        ServiceClient.AuctionService.Auction[] GetAuctions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionService/GetAuctions", ReplyAction="http://tempuri.org/IAuctionService/GetAuctionsResponse")]
        System.Threading.Tasks.Task<ServiceClient.AuctionService.Auction[]> GetAuctionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionService/GetAuction", ReplyAction="http://tempuri.org/IAuctionService/GetAuctionResponse")]
        ServiceClient.AuctionService.Auction GetAuction(string varenummer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionService/GetAuction", ReplyAction="http://tempuri.org/IAuctionService/GetAuctionResponse")]
        System.Threading.Tasks.Task<ServiceClient.AuctionService.Auction> GetAuctionAsync(string varenummer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionService/Bid", ReplyAction="http://tempuri.org/IAuctionService/BidResponse")]
        string Bid(string varenummer, int budpris, string kundenavn, string kundetelefon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionService/Bid", ReplyAction="http://tempuri.org/IAuctionService/BidResponse")]
        System.Threading.Tasks.Task<string> BidAsync(string varenummer, int budpris, string kundenavn, string kundetelefon);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuctionServiceChannel : ServiceClient.AuctionService.IAuctionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuctionServiceClient : System.ServiceModel.ClientBase<ServiceClient.AuctionService.IAuctionService>, ServiceClient.AuctionService.IAuctionService {
        
        public AuctionServiceClient() {
        }
        
        public AuctionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuctionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuctionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuctionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceClient.AuctionService.Auction[] GetAuctions() {
            return base.Channel.GetAuctions();
        }
        
        public System.Threading.Tasks.Task<ServiceClient.AuctionService.Auction[]> GetAuctionsAsync() {
            return base.Channel.GetAuctionsAsync();
        }
        
        public ServiceClient.AuctionService.Auction GetAuction(string varenummer) {
            return base.Channel.GetAuction(varenummer);
        }
        
        public System.Threading.Tasks.Task<ServiceClient.AuctionService.Auction> GetAuctionAsync(string varenummer) {
            return base.Channel.GetAuctionAsync(varenummer);
        }
        
        public string Bid(string varenummer, int budpris, string kundenavn, string kundetelefon) {
            return base.Channel.Bid(varenummer, budpris, kundenavn, kundetelefon);
        }
        
        public System.Threading.Tasks.Task<string> BidAsync(string varenummer, int budpris, string kundenavn, string kundetelefon) {
            return base.Channel.BidAsync(varenummer, budpris, kundenavn, kundetelefon);
        }
    }
}
